# Generated by Django 6.0.3 on 2026-04-16 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=150)),
                ('documento_identidad', models.CharField(max_length=30)),
                ('correo_electronico', models.EmailField(max_length=150)),
                ('telefono_contacto', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'El telefono debe contener solo numeros.')])),
                ('tipo_solicitud', models.CharField(choices=[('academica', 'Academica'), ('administrativa', 'Administrativa'), ('tecnica', 'Tecnica'), ('otra', 'Otra')], max_length=20)),
                ('asunto', models.CharField(max_length=150)),
                ('descripcion_detallada', models.TextField()),
                ('fecha_solicitud', models.DateField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='solicitudes/')),
            ],
        ),
    ]
