# Generated by Django 6.0.4 on 2026-04-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('documento_identidad', models.CharField(max_length=50, verbose_name='Documento de identidad')),
                ('correo_electronico', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('fecha_asistencia', models.DateField(verbose_name='Fecha de asistencia')),
                ('hora_ingreso', models.TimeField(verbose_name='Hora de ingreso')),
                ('hora_salida', models.TimeField(verbose_name='Hora de salida')),
                ('presente', models.BooleanField(default=False, verbose_name='Presente')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha_asistencia', '-hora_ingreso'],
            },
        ),
    ]
